defaults:
  - hydra/job_logging: disabled
  - hydra/output_subdir: null
hydra:
  output_subdir: null
  run:
    dir: .
main:
  experiment_name_prefix: faster_rcnn
  seed: 1
  trains: False
  paths:
    train: '/home/student/data/train'
    test: '/home/student/data/test'
    example: './data/example_images'
    logs: 'logs/'
  max_img_size: 224
train:
  num_epochs: 20
  batch_size: 32
  save_model: True
  lr:
    lr_value: 1e-3
    lr_decay: 15
    lr_gamma: 0.1
    lr_step_size: 3
data:
  img_size: 224
