name: lab_hw2_env
channels:
  - default
  - pytorch
  - conda-forge
dependencies:
  - python=3.8
  - opencv=4.5.2
  - pytorch=1.9.0
  - pytorch-lightning=1.3.6
  - pandas=1.2.4
  - matplotlib=3.4.2
  - pip
  - pip:
    - gdown==3.13.0
    - git+https://github.com/almog-gueta/vision.git
    - seaborn==0.11.1
    - hydra-core==1.0.0
    - schema==0.7.4 
    - tqdm==4.61.1 